INSERT INTO [AppStandardReference]([StandardReferenceID],[StandardReferenceName],[ItemLength],[IsUsedBySystem],[IsActive],[StandardReferenceGroup],[Note],[LastUpdateDateTime],[LastUpdateByUserID],[HasCOA],[IsNumericValue])
VALUES(N'DicomCode',N'Dicom Code',100,0,1,'','',GETDATE(),N'naufal',NULL,NULL);

INSERT INTO [AppStandardReferenceItem](
    [StandardReferenceID],
    [ItemID],
    [ItemName],
    [Note],
    [IsUsedBySystem],
    [IsActive],
    [LastUpdateDateTime],
    [LastUpdateByUserID],
    [ReferenceID],
    [coaID],
    [subledgerID],
    [CustomField],
    [LineNumber],
    [NumericValue],
    [CustomField2]
)
VALUES
(N'DicomCode', N'ANN', N'ANN', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'AR', N'AR', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'ARCHIVE', N'ARCHIVE', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'AS', N'AS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'ASMT', N'ASMT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'AU', N'AU', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'BDUS', N'BDUS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'BI', N'BI', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'BMD', N'BMD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'CAD', N'CAD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'CAPTURE', N'CAPTURE', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'CD', N'CD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'CF', N'CF', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'COMP', N'COMP', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'CP', N'CP', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'CR', N'CR', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'CS', N'CS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'CT', N'CT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'CTPROTOCOL', N'CTPROTOCOL', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DD', N'DD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DF', N'DF', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DG', N'DG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DM', N'DM', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DMS', N'DMS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DOC', N'DOC', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DOCD', N'DOCD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DS', N'DS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DSS', N'DSS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'DX', N'DX', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'EC', N'EC', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'ECG', N'ECG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'EEG', N'EEG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'EMG', N'EMG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'EOG', N'EOG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'EPS', N'EPS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'ES', N'ES', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'F', N'F', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'FA', N'FA', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'FC', N'FC', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'FID', N'FID', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'FILMD', N'FILMD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'FP', N'FP', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'FS', N'FS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'GM', N'GM', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'H', N'H', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'HC', N'HC', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'HD', N'HD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'IO', N'IO', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'IOL', N'IOL', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'IVOCT', N'IVOCT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'IVUS', N'IVUS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'KER', N'KER', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'KO', N'KO', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'LEN', N'LEN', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'LOG', N'LOG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'LP', N'LP', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'LS', N'LS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'M', N'M', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'M3D', N'M3D', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'MA', N'MA', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'MC', N'MC', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'MCD', N'MCD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'MEDIM', N'MEDIM', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'MG', N'MG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'MP', N'MP', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'MR', N'MR', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'MS', N'MS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'NEARLINE', N'NEARLINE', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'NM', N'NM', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OAM', N'OAM', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OCT', N'OCT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OFFLINE', N'OFFLINE', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'ONLINE', N'ONLINE', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OP', N'OP', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OPM', N'OPM', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OPR', N'OPR', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OPT', N'OPT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OPTBSV', N'OPTBSV', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OPTENF', N'OPTENF', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OPV', N'OPV', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OSS', N'OSS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'OT', N'OT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'PA', N'PA', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'PLAN', N'PLAN', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'POS', N'POS', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'PR', N'PR', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'PRINT', N'PRINT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'PT', N'PT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'PX', N'PX', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'REG', N'REG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RESP', N'RESP', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RF', N'RF', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RG', N'RG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RT', N'RT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RTDOSE', N'RTDOSE', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RTIMAGE', N'RTIMAGE', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RTPLAN', N'RTPLAN', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RTRECORD', N'RTRECORD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RTSTRUCT', N'RTSTRUCT', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'RWV', N'RWV', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'SEG', N'SEG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'SM', N'SM', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'SMR', N'SMR', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'SR', N'SR', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'SRF', N'SRF', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'ST', N'ST', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'STAIN', N'STAIN', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'TEXTUREMAP', N'TEXTUREMAP', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'TG', N'TG', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'U', N'U', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'UNAVAILABLE', N'UNAVAILABLE', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'US', N'US', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'VA', N'VA', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'VF', N'VF', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'VIDD', N'VIDD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'WSD', N'WSD', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'XA', N'XA', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(N'DicomCode', N'XC', N'XC', '', 0, 1, GETDATE(), N'naufal', NULL,NULL,NULL,NULL,NULL,NULL,NULL);



