//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temiang.Avicenna.Module.RADT.Ppra
{
    public partial class PpraHistoryPopup
    {
        /// <summary>litHeader control.</summary>
        protected global::System.Web.UI.WebControls.Literal litHeader;

        /// <summary>litHistory control.</summary>
        protected global::System.Web.UI.WebControls.Literal litHistory;
    }
}
