//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temiang.Avicenna.Module.RADT.Ppra
{
    public partial class PpraReview
    {
        /// <summary>litPatientHeader control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPatientHeader;

        /// <summary>litMedicalNo control.</summary>
        protected global::System.Web.UI.WebControls.Literal litMedicalNo;

        /// <summary>litRegistrationNo control.</summary>
        protected global::System.Web.UI.WebControls.Literal litRegistrationNo;

        /// <summary>litRegistrationDate control.</summary>
        protected global::System.Web.UI.WebControls.Literal litRegistrationDate;

        /// <summary>litParamedicName control.</summary>
        protected global::System.Web.UI.WebControls.Literal litParamedicName;

        /// <summary>litGuarantorName control.</summary>
        protected global::System.Web.UI.WebControls.Literal litGuarantorName;

        /// <summary>litServiceUnit control.</summary>
        protected global::System.Web.UI.WebControls.Literal litServiceUnit;

        /// <summary>litRoomBed control.</summary>
        protected global::System.Web.UI.WebControls.Literal litRoomBed;

        /// <summary>litGender control.</summary>
        protected global::System.Web.UI.WebControls.Literal litGender;

        /// <summary>litDobAge control.</summary>
        protected global::System.Web.UI.WebControls.Literal litDobAge;

        /// <summary>litAllergies control.</summary>
        protected global::System.Web.UI.WebControls.Literal litAllergies;

        /// <summary>litPendingPrescriptions control.</summary>
        protected global::System.Web.UI.WebControls.Literal litPendingPrescriptions;

        /// <summary>litRasproForm control.</summary>
        protected global::System.Web.UI.WebControls.Literal litRasproForm;

        /// <summary>soapInfoCtl control.</summary>
        protected global::Temiang.Avicenna.CustomControl.SoapInfoCtl soapInfoCtl;

        /// <summary>grdLab control.</summary>
        protected global::Telerik.Web.UI.RadGrid grdLab;

        /// <summary>grdRad control.</summary>
        protected global::Telerik.Web.UI.RadGrid grdRad;

        /// <summary>hdnPrescNo control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnPrescNo;

        /// <summary>hdnAction control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnAction;

        /// <summary>btnAction control.</summary>
        protected global::System.Web.UI.WebControls.Button btnAction;
    }
}
