//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl
{


    public partial class IgdPeCtl
    {

        /// <summary>
        /// ddlTriage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadDropDownList ddlTriage;

        /// <summary>
        /// trCaseType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trCaseType;

        /// <summary>
        /// rblCaseType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rblCaseType;

        /// <summary>
        /// questJalanNapas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questJalanNapas;

        /// <summary>
        /// questPernapasan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questPernapasan;

        /// <summary>
        /// questSirkulasi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questSirkulasi;

        /// <summary>
        /// questPenilaianBayi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questPenilaianBayi;

        /// <summary>
        /// questDisabilitas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questDisabilitas;

        /// <summary>
        /// questEksposur control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questEksposur;

        /// <summary>
        /// gcsCtl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.GcsCtl gcsCtl;

        /// <summary>
        /// questKepalaLeher control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questKepalaLeher;

        /// <summary>
        /// questThorax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questThorax;

        /// <summary>
        /// questAbdomenPelvis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questAbdomenPelvis;

        /// <summary>
        /// questOth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questOth;

        /// <summary>
        /// questAncillaryExam control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Temiang.Avicenna.Module.RADT.Emr.AssessmentCtl.QuestionCtl questAncillaryExam;
    }
}
