INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('BCG','BCG',1,3,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('CAM','Campak / MMR',3,9,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('CVD','COVID-19',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('DG','Dengue',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('DPT','DPT',5,4,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('DT','DT',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('FLU','Influenza',1,14,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('HIB','Hib',4,5,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('HPA','Hepatitis A',2,12,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('HPB','Hepatitis B (HB)',4,1,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('HPV','HPV',3,14,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('HZ','Herpes zoster',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('IPV','IPV',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('JE','Japanese encephalitis (JE)',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('MMR','MMR',2,10,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('MN','Meningitis meningokokus',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('OPV','OPV (Polio)',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('PCV','PCV (Polio)',4,6,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('PPV','PPV',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('RB','Rabies',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('ROT','Rotavirus',3,7,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('TD','Td',10,20,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('TYP','Typhoid',5,11,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('VAR','Varisela',2,13,NULL,'sci')
INSERT INTO [dbo].[Immunization]([ImmunizationID],[ImmunizationName],[MaxCount],[IndexNo],[LastUpdateDateTime],[LastUpdateByUserID]) VALUES ('YF','Yellow fever',10,20,NULL,'sci')